services:
  mvd-browser:
    build: .
    container_name: mvd-browser
    ports:
      - "7650:7650"
    environment:
      PKR_URL: "http://host.docker.internal:7450"
      CAT_URL: "http://host.docker.internal:7451"
    extra_hosts:
      - "host.docker.internal:host-gateway"